
name: Notify Slack on Issues

on:
  issues:
    types: [opened, closed, reopened, assigned, unassigned, labeled, unlabeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue notification to Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": "ğŸ› Issue *${{ github.event.action }}* in *${{ github.repository }}*\nğŸ‘‰ <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>\nğŸ§‘ Author: *${{ github.event.issue.user.login }}*\nğŸ”– State: *${{ github.event.issue.state }}*\nğŸ‘¤ Assignees: ${{ toJson(github.event.issue.assignees) }}\nğŸ·ï¸ Labels: ${{ toJson(github.event.issue.labels) }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ISSUES_URL }}
